# Ansible Inventory — auto-generated by Terraform
# Do not edit manually; re-run `terraform apply` to regenerate.

[ubuntu]
%{ for ip in ubuntu_ips ~}
${ip} ansible_user=ubuntu
%{ endfor ~}

[amazon]
%{ for ip in amazon_ips ~}
${ip} ansible_user=ec2-user
%{ endfor ~}

[all:children]
ubuntu
amazon

[all:vars]
ansible_ssh_private_key_file=~/.ssh/${key_name}.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=auto_silent
